import { Router } from "express";
import { authenticate, requireModule } from "../../middleware/auth.js";
import * as ctrl from "./billing.controller.js";
const router = Router();
router.use(authenticate);
router.use(requireModule("billing"));
router.get("/invoices",                  ctrl.listInvoices);
router.get("/invoices/reconciliation",   ctrl.reconciliation);
router.get("/invoices/:id",              ctrl.getInvoice);
router.post("/invoices",                 ctrl.createInvoice);
router.post("/invoices/:id/payment",     ctrl.payment);
export default router;
