import { Router } from "express";
import { authenticate } from "../../middleware/auth.js";
import * as ctrl from "./radiology.controller.js";
const router = Router();
router.use(authenticate);
router.get("/",             ctrl.list);
router.get("/:id",          ctrl.getOne);
router.post("/",            ctrl.create);
router.patch("/:id/report", ctrl.report);
export default router;
